services:
    mysql:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=nebbie
        ports:
            - 3306:33306
        volumes:
            - ./mysql_data:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - "0.0.0.0:8080:8080"
        depends_on:
            - mysql
        environment:
            - ADMINER_HOST=mysql
            - ADMINER_USER=root
            - ADMINER_PASSWORD=secret
            - ADMINER_DEFAULT_SERVER=mysql
            - ADMINER_DEFAULT_PORT=33306
    consumer:
        image: nebbiearcane/mudcompiler:latest
        entrypoint: ["/usr/bin/bash","-c"]
        volumes:
            - ./:/app
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        ports:
            - 4000:4000
            - 4001:4001
            - 4002:4002
            - 10000:10000
        environment:
            - SERVER_PORT=4000
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=nebbie
            - MYSQL_USER=root
            - MYSQL_PORT=33306
            - MYSQL_PASSWORD=secret
            - DATABASE_URL=mysql://root:secret@mysql:33306/nebbie
            - HOME=/app
        depends_on:
            - mysql
            - adminer