#!/bin/bash
if [ "$3." = "." ] ; then
   echo "Uso $0 major minor release"
   cat versione.in
   exit
fi
echo "$1" >versione.in
echo "$2" >>versione.in
echo "$3" >>versione.in
. compilazione
gcc mkver.c -o mkver
echo Done.
