name: compile
description: Compile myst binary and upload workflow artifact
inputs:
  build_env:
    description: Environment name passed to build.sh
    required: true
  mysql_host:
    description: MySQL host for build.sh
    required: false
    default: localhost
  mysql_user:
    description: MySQL user for build.sh
    required: false
    default: nebbie
  mysql_db:
    description: MySQL database name for build.sh
    required: false
    default: nebbie
  mysql_password:
    description: MySQL password for build.sh
    required: false
    default: secret
  mysql_port:
    description: MySQL port for build.sh
    required: false
    default: 3306
  excludes:
    description: Excludes
    required: true
    default: latest,prerelease
  dryrun:
    description: Dry run
    required: false
    default: true
runs:
  using: composite
  steps:
    - name: Compile myst
      shell: bash
      env:
        MYSQL_HOST: ${{ inputs.mysql_host }}
        MYSQL_USER: ${{ inputs.mysql_user }}
        MYSQL_PASSWORD: ${{ inputs.MYSQL_PASSWORD }}
        MYSQL_PORT: ${{ inputs.mysql_port }}
        MYSQL_DB: ${{ inputs.mysql_db }}
      run: |
        git config --global --add safe.directory /__w/Server/Server
        ./build.sh "${{ inputs.build_env }}"

    - name: Verify myst binary
      shell: bash
      run: test -x mudroot/myst

    - name: Prepare myst release binary
      shell: bash
      if: !inputs.dryrun
      env:
        BUILD_ENV: ${{ inputs.build_env }}
      run: |
        RELEASE_NAME="myst-${BUILD_ENV}"
        chmod +x "./mudroot/myst"
        mkdir -p ./assets
        cp mudroot/myst "./assets/myst_${RELEASE_NAME}"
        ./mudroot/myst -V > "./assets/myst_${RELEASE_NAME}-version.txt" 2>&1 || true
        ./mudroot/myst -c > "./assets/myst_${RELEASE_NAME}-config.txt" 2>&1 || true
        echo "MYST_RELEASE_NAME=${RELEASE_NAME}" >> "$GITHUB_ENV"
    - name: Simulate myst release binary
      shell: bash
      if: inputs.dryrun
      env:
        BUILD_ENV: ${{ inputs.build_env }}
      run: |
        RELEASE_NAME="myst-${BUILD_ENV}"
        touchc "./mudroot/myst"
        mkdir -p ./assets
        cp mudroot/myst "./assets/myst_${RELEASE_NAME}"
        echo "Version dryrun" > "./assets/myst_${RELEASE_NAME}-version.txt" 2>&1 || true
        echo "Config dryrun" > "./assets/myst_${RELEASE_NAME}-config.txt" 2>&1 || true
        echo "MYST_RELEASE_NAME=${RELEASE_NAME}" >> "$GITHUB_ENV"
        v=`cat  "./assets/myst_${RELEASE_NAME}-version.txt"`
        c=`cat  "./assets/myst_${RELEASE_NAME}-config.txt"`
        b="Version: $v\nConfig: $c"
        b="${b//'%'/'%25'}"                               # Multiline escape sequences for %
        b="${b//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
        b="${b//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
        echo "RELEASE_BODY=$b" >> $GITHUB_OUTPUT          # <--- Set environment variable
      

    # - name: Store myst executable as workflow artifact
    #   if: github.ref_type != 'tag'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ env.MYST_RELEASE_NAME }}
    #     path: |
    #       ${{ env.MYST_RELEASE_NAME }}
    #       myst-version.txt
    #       myst-config.txt
    #     retention-days: 30

    - id: keydb
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
        token: ${{ inputs.token }}
        excludes: ${{ inputs.excludes }}    
    - name: Prepare a release
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: ./assets/*
        tag: ${{ github.ref }}
        release_id: ${{ steps.keydb.outputs.id }}
        release_name: "Built from ${{ github.ref }} by ${{ github.actor }} "
        body: |
          ${{ steps.read_release.outputs.RELEASE_BODY }}  # <--- Use environment variables that was created earlier
        overwrite: true
        draft: ${{ inputs.build_env == 'devel'}}
        prerelease: ${{ inputs.build_env == 'staging'}}
        make_latest: ${{ inputs.build_env == 'production'}}
