#!/bin/sh
# Actual mud home
home="/home/nebbie/Run"
#End configuration
cd $(dirname $0)
exec >/dev/null 2>&1
PATH=/mud:/mud/lib:$PATH
touch mud_demon.last
umask 006
ulimit -c unlimited
FINE=0
touch HALT.NOT
touch STOP.NOT
touch RELOAD.NOT
rm -f HALT
rm -f STOP
rm -f RELOAD
while [ $FINE = 0 ]
do
 if [ -f RELOAD ] ; then
	#new version requested
	exit
 fi
 if [ -f HALT ] ; then
    if [ -f lib/myst.pid ] ; then
       pid=`cat lib/myst.pid`
       kill -USR2 $pid
       exit
    fi
 fi
 ps -ax >tmp.log
 if grep -i "myst" tmp.log >/dev/null ; then
    sleep 2m
 else
    if [ -f STOP ] ; then
       sleep 1m
    else
       date >>Vai.log
       echo Lancio Myst >>Vai.log
       if [ -f lib/REBOOT.NOW ] ; then
          rm -f lib/REBOOT.DONE
          mv lib/REBOOT.NOW lib/REBOOT.DONE
       fi
	./lib/backup-pg
	./lib/backup-rent
        ./startmyst
       touch ./LastRun
       sleep 3m
    fi
 fi

done
