#!/bin/sh
cd $(dirname $0)
umask 006
mkdir -p ./logs
ulimit -c unlimited
cp log.txt lastlog.txt
./checkcrash 
#./cleanreg
# To be fixed
if [ -f ../Deploy/mystnew ] ; then
   saved=mystsv`/bin/date +%Y%m%d`
   cp myst $saved
   cp -f ../Deploy/mystnew myst
   rm -f ../Deploy/mystnew
fi
#chmod +s myst
LOGNAME=`date +%Y%m%d.%H%M`

DEST=giovanni@gargani.it
subj=`date +%Y%m%d.%H`

if grep "fine modifica" lastlog.txt > checkpq.txt ; then
       cat checkpq.txt | mail $DEST  -s "[PQ spesi] : $subj"
fi

mv log.txt log$LOGNAME.txt
zip -m ./logs/log$LOGNAME.zip log$LOGNAME.txt
if [ -f core ] ; then
   mv core ./logs/core$LOGNAME
fi
busyspace=`du -s ./logs | cut -f1`
echo "busyspace = $busyspace" >>./logs/removed.log
(
cd  ./logs
chown nebbie. *
chmod 660 log*
if [ $busyspace -gt 120000 ] ; then
   for todel in `ls -t log* | tail -5` ; do
     rm -f $todel
     echo "Rimosso $todel" >>removed.log
   done
fi
)
touch log.txt
chown nebbie. log.txt
chmod 660 log.txt
sleep 1
#Todo rivedere build aree
#if [ -f REBUILD ] ; then
#  mv -f REBUILD REBUILD.LAST
#  cd /mud/lib
#  date >aload.log
#  ./aree.load >>aload.log
#  cat aload.log | mail nebbie-builder-l@nebbie.it -s "World rebuild"
#  chown mud. *
#  cd ..
#fi
chown nebbie. *.log
#./myst -L -M >&log.txt &
./myst -L -M 4001  >log.txt 2>log.txt &
