#!/usr/bin/php
<?php
/**
 * Generate MySQL ENUM sync C++ from ODB changelog XML (account-mysql.xml).
 *
 * usage: generate-enum-sync.php <account-mysql.xml> <out.cxx> <out.hxx>
 */
declare(strict_types=1);

if ($argc !== 4) {
    fwrite(STDERR, "usage: generate-enum-sync.php <account-mysql.xml> <out.cxx> <out.hxx>\n");
    exit(1);
}

$xmlPath = $argv[1];
$outCxx = $argv[2];
$outHxx = $argv[3];

if (!is_readable($xmlPath)) {
    fwrite(STDERR, "cannot read: {$xmlPath}\n");
    exit(1);
}

$xml = file_get_contents($xmlPath);
if ($xml === false) {
    fwrite(STDERR, "cannot read: {$xmlPath}\n");
    exit(1);
}

$columns = collect_enum_columns($xml);
file_put_contents($outHxx, emit_header());
file_put_contents($outCxx, emit_source($columns));
fwrite(STDOUT, 'enum-sync: ' . count($columns) . ' ENUM column(s) -> ' . basename($outCxx) . "\n");

function collect_enum_columns(string $xml): array
{
    if (!preg_match('/<model\b[^>]*>(.*)<\/model>/s', $xml, $modelMatch)) {
        fwrite(STDERR, "no <model> in changelog XML\n");
        exit(1);
    }

    $columns = [];
    if (!preg_match_all('/<table name="([^"]+)"[^>]*>(.*?)<\/table>/s', $modelMatch[1], $tables, PREG_SET_ORDER)) {
        return $columns;
    }

    foreach ($tables as $table) {
        $tableName = $table[1];
        if (!preg_match_all(
            '/<column name="([^"]+)" type="(ENUM\([^"]+\))"(?:[^>]*\bnull="(true|false)")?[^>]*\/>/',
            $table[2],
            $tableCols,
            PREG_SET_ORDER
        )) {
            continue;
        }

        foreach ($tableCols as $column) {
            $columns[] = [
                'table' => $tableName,
                'column' => $column[1],
                'enum_sql' => $column[2],
                'literals' => parse_enum_literals($column[2]),
                'null_clause' => column_null_clause(
                    (isset($column[3]) && $column[3] !== '') ? $column[3] : null
                ),
            ];
        }
    }

    return $columns;
}

function parse_enum_literals(string $enumType): array
{
    if (!preg_match('/^ENUM\((.*)\)$/i', trim($enumType), $match)) {
        throw new RuntimeException("not an ENUM type: {$enumType}");
    }

    $literals = [];
    if (preg_match_all("/'((?:''|[^'])*)'/", $match[1], $parts, PREG_SET_ORDER)) {
        foreach ($parts as $part) {
            $literals[] = str_replace("''", "'", $part[1]);
        }
    }

    return $literals;
}

function column_null_clause(?string $nullAttr): string
{
    return $nullAttr === 'true' ? 'NULL DEFAULT NULL' : 'NOT NULL';
}

function enum_like_pattern(string $literal): string
{
    return "%''" . str_replace("'", "''", $literal) . "''%";
}

function cpp_escape(string $value): string
{
    return str_replace(['\\', '"'], ['\\\\', '\\"'], $value);
}

function emit_header(): string
{
    return <<<'CPP'
// Generated by shutils/generate-enum-sync.php — do not edit.

#ifndef SRC_ODB_ACCOUNT_ENUM_SYNC_MYSQL_HXX_
#define SRC_ODB_ACCOUNT_ENUM_SYNC_MYSQL_HXX_

#include <odb/database.hxx>

namespace odb_enum_sync {

void sync_mysql_enums(odb::database& db);

}  // namespace odb_enum_sync

#endif  // SRC_ODB_ACCOUNT_ENUM_SYNC_MYSQL_HXX_
CPP;
}

function emit_source(array $columns): string
{
    $lines = [
        '// Generated by shutils/generate-enum-sync.php — do not edit.',
        '',
        '#include "account-enum-sync-mysql.hxx"',
        '',
        '#include <cstdlib>',
        '#include <string>',
        '',
        '#include <mysql/mysql.h>',
        '#include <odb/mysql/connection.hxx>',
        '#include <odb/transaction.hxx>',
        '',
        'namespace odb_enum_sync {',
        'namespace {',
        '',
        'unsigned long long enum_sync_scalar(odb::database& db, const std::string& sql) {',
        '  odb::connection_ptr owned;',
        '  odb::connection& conn = odb::transaction::has_current()',
        '      ? odb::transaction::current().connection()',
        '      : *(owned = db.connection());',
        '  auto& mc = static_cast<odb::mysql::connection&>(conn);',
        '  MYSQL* h = mc.handle();',
        '  if (mysql_query(h, sql.c_str()) != 0) {',
        '    return 0;',
        '  }',
        '  MYSQL_RES* res = mysql_store_result(h);',
        '  unsigned long long n = 0;',
        '  if (res) {',
        '    if (MYSQL_ROW row = mysql_fetch_row(res)) {',
        '      if (row[0]) {',
        '        n = std::strtoull(row[0], nullptr, 10);',
        '      }',
        '    }',
        '    mysql_free_result(res);',
        '  }',
        '  return n;',
        '}',
        '',
        'bool column_exists(odb::database& db, const char* table, const char* column) {',
        '  const std::string sql =',
        '      "SELECT COUNT(*) FROM information_schema.COLUMNS "',
        '      "WHERE TABLE_SCHEMA = DATABASE() "',
        '      "AND TABLE_NAME = \'" + std::string(table) + "\' "',
        '      "AND COLUMN_NAME = \'" + std::string(column) + "\'";',
        '  return enum_sync_scalar(db, sql) > 0;',
        '}',
        '',
        'bool column_type_contains(odb::database& db, const char* table,',
        '                          const char* column, const char* pattern) {',
        '  const std::string sql =',
        '      "SELECT COUNT(*) FROM information_schema.COLUMNS "',
        '      "WHERE TABLE_SCHEMA = DATABASE() "',
        '      "AND TABLE_NAME = \'" + std::string(table) + "\' "',
        '      "AND COLUMN_NAME = \'" + std::string(column) + "\' "',
        '      "AND COLUMN_TYPE LIKE \'" + std::string(pattern) + "\'";',
        '  return enum_sync_scalar(db, sql) > 0;',
        '}',
        '',
        '}  // namespace',
        '',
        'void sync_mysql_enums(odb::database& db) {',
    ];

    if (count($columns) === 0) {
        $lines[] = '  // No ENUM columns in account-mysql.xml';
    } else {
        foreach ($columns as $col) {
            $table = cpp_escape($col['table']);
            $column = cpp_escape($col['column']);
            $lines[] = "  {  // {$col['table']}.{$col['column']}";
            $lines[] = "    const char* table = \"{$table}\";";
            $lines[] = "    const char* column = \"{$column}\";";
            $lines[] = '    if (!column_exists(db, table, column)) {';
            $lines[] = '      // create_schema / migrate handle new columns';
            $lines[] = '    } else {';
            $lines[] = '      bool needs_alter = false;';
            foreach ($col['literals'] as $literal) {
                $pattern = cpp_escape(enum_like_pattern($literal));
                $lines[] = "      if (!column_type_contains(db, table, column, \"{$pattern}\")) { needs_alter = true; }";
            }
            $alterSql = cpp_escape(
                'ALTER TABLE `' . $col['table'] . '` MODIFY COLUMN `' . $col['column'] . '` '
                . $col['enum_sql'] . ' ' . $col['null_clause']
            );
            $lines[] = '      if (needs_alter) {';
            $lines[] = "        db.execute(\"{$alterSql}\");";
            $lines[] = '      }';
            $lines[] = '    }';
            $lines[] = '  }';
        }
    }

    $lines[] = '}';
    $lines[] = '';
    $lines[] = '}  // namespace odb_enum_sync';
    $lines[] = '';

    return implode("\n", $lines);
}
