#!/usr/bin/php
<?php
/**
 * Generate MySQL ENUM sync C++ from ODB changelog XML (account-mysql.xml).
 *
 * usage: generate-enum-sync.php <account-mysql.xml> <out.cxx> <out.hxx>
 */
declare(strict_types=1);

if ($argc !== 4) {
    fwrite(STDERR, "usage: generate-enum-sync.php <account-mysql.xml> <out.cxx> <out.hxx>\n");
    exit(1);
}

$xmlPath = $argv[1];
$outCxx = $argv[2];
$outHxx = $argv[3];

if (!is_readable($xmlPath)) {
    fwrite(STDERR, "cannot read: {$xmlPath}\n");
    exit(1);
}

$xml = simplexml_load_file($xmlPath);
if ($xml === false) {
    fwrite(STDERR, "invalid XML: {$xmlPath}\n");
    exit(1);
}

$xml->registerXPathNamespace('odb', 'http://www.codesynthesis.com/xmlns/odb/changelog');
$models = $xml->xpath('//odb:model');
if ($models === false || count($models) === 0) {
    fwrite(STDERR, "no <model> in {$xmlPath}\n");
    exit(1);
}

$columns = collect_enum_columns($models[0]);
file_put_contents($outHxx, emit_header());
file_put_contents($outCxx, emit_source($columns));
fwrite(STDOUT, 'enum-sync: ' . count($columns) . ' ENUM column(s) -> ' . basename($outCxx) . "\n");

function collect_enum_columns(SimpleXMLElement $model): array
{
    $columns = [];
    $model->registerXPathNamespace('odb', 'http://www.codesynthesis.com/xmlns/odb/changelog');
    $tables = $model->xpath('odb:table') ?: [];

    foreach ($tables as $table) {
        $tableName = (string) $table['name'];
        $tableCols = $table->xpath('odb:column') ?: [];
        foreach ($tableCols as $column) {
            $columnType = (string) $column['type'];
            if (stripos($columnType, 'ENUM(') !== 0) {
                continue;
            }
            $columns[] = [
                'table' => $tableName,
                'column' => (string) $column['name'],
                'enum_sql' => $columnType,
                'literals' => parse_enum_literals($columnType),
                'null_clause' => column_null_clause(isset($column['null']) ? (string) $column['null'] : null),
            ];
        }
    }

    return $columns;
}

function parse_enum_literals(string $enumType): array
{
    if (!preg_match('/^ENUM\((.*)\)$/i', trim($enumType), $match)) {
        throw new RuntimeException("not an ENUM type: {$enumType}");
    }

    $literals = [];
    if (preg_match_all("/'((?:''|[^'])*)'/", $match[1], $parts, PREG_SET_ORDER)) {
        foreach ($parts as $part) {
            $literals[] = str_replace("''", "'", $part[1]);
        }
    }

    return $literals;
}

function column_null_clause(?string $nullAttr): string
{
    return $nullAttr === 'true' ? 'NULL DEFAULT NULL' : 'NOT NULL';
}

function enum_like_pattern(string $literal): string
{
    return "%''" . str_replace("'", "''", $literal) . "''%";
}

function cpp_escape(string $value): string
{
    return str_replace(['\\', '"'], ['\\\\', '\\"'], $value);
}

function emit_header(): string
{
    return <<<'CPP'
// Generated by shutils/generate-enum-sync.php — do not edit.

#ifndef SRC_ODB_ACCOUNT_ENUM_SYNC_MYSQL_HXX_
#define SRC_ODB_ACCOUNT_ENUM_SYNC_MYSQL_HXX_

#include <odb/database.hxx>

namespace odb_enum_sync {

void sync_mysql_enums(odb::database& db);

}  // namespace odb_enum_sync

#endif  // SRC_ODB_ACCOUNT_ENUM_SYNC_MYSQL_HXX_
CPP;
}

function emit_source(array $columns): string
{
    $lines = [
        '// Generated by shutils/generate-enum-sync.php — do not edit.',
        '',
        '#include "odb/account-enum-sync-mysql.hxx"',
        '',
        '#include <cstddef>',
        '#include <cstring>',
        '',
        'namespace odb_enum_sync {',
        'namespace {',
        '',
        'bool column_exists(odb::database& db, const char* table, const char* column) {',
        '  odb::result r(db.execute(',
        '      "SELECT COUNT(*) FROM information_schema.COLUMNS "',
        '      "WHERE TABLE_SCHEMA = DATABASE() "',
        '      "AND TABLE_NAME = \'" + std::string(table) + "\' "',
        '      "AND COLUMN_NAME = \'" + std::string(column) + "\'"));',
        '  odb::result::iterator i(r.begin());',
        '  return i != r.end() && static_cast<std::size_t>((*i)[0]) > 0;',
        '}',
        '',
        'bool column_type_contains(odb::database& db, const char* table,',
        '                          const char* column, const char* pattern) {',
        '  odb::result r(db.execute(',
        '      "SELECT COUNT(*) FROM information_schema.COLUMNS "',
        '      "WHERE TABLE_SCHEMA = DATABASE() "',
        '      "AND TABLE_NAME = \'" + std::string(table) + "\' "',
        '      "AND COLUMN_NAME = \'" + std::string(column) + "\' "',
        '      "AND COLUMN_TYPE LIKE \'" + std::string(pattern) + "\'"));',
        '  odb::result::iterator i(r.begin());',
        '  return i != r.end() && static_cast<std::size_t>((*i)[0]) > 0;',
        '}',
        '',
        '}  // namespace',
        '',
        'void sync_mysql_enums(odb::database& db) {',
    ];

    if (count($columns) === 0) {
        $lines[] = '  // No ENUM columns in account-mysql.xml';
    } else {
        foreach ($columns as $col) {
            $table = cpp_escape($col['table']);
            $column = cpp_escape($col['column']);
            $lines[] = "  {  // {$col['table']}.{$col['column']}";
            $lines[] = "    const char* table = \"{$table}\";";
            $lines[] = "    const char* column = \"{$column}\";";
            $lines[] = '    if (!column_exists(db, table, column)) {';
            $lines[] = '      // create_schema / migrate handle new columns';
            $lines[] = '    } else {';
            $lines[] = '      bool needs_alter = false;';
            foreach ($col['literals'] as $literal) {
                $pattern = cpp_escape(enum_like_pattern($literal));
                $lines[] = "      if (!column_type_contains(db, table, column, \"{$pattern}\")) { needs_alter = true; }";
            }
            $alterSql = cpp_escape(
                'ALTER TABLE `' . $col['table'] . '` MODIFY COLUMN `' . $col['column'] . '` '
                . $col['enum_sql'] . ' ' . $col['null_clause']
            );
            $lines[] = '      if (needs_alter) {';
            $lines[] = "        db.execute(\"{$alterSql}\");";
            $lines[] = '      }';
            $lines[] = '    }';
            $lines[] = '  }';
        }
    }

    $lines[] = '}';
    $lines[] = '';
    $lines[] = '}  // namespace odb_enum_sync';
    $lines[] = '';

    return implode("\n", $lines);
}
