/*
 * spells2.hpp
 *
 *  Created on: 14 feb 2018
 *      Author: giovanni
 *
 * Licensed Material - Property of Hex Keep s.r.l.
 * (c) Copyright Hex Keep s.r.l. 2012-2014
 */

#ifndef __SPELLS2_HPP
#define __SPELLS2_HPP
#include "typedefs.hpp"
struct PolyType {
	char name[20];
	int  level;
	int  number;
};
void cast_resurrection(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_major_track(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_minor_track(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mana(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_armor(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mirror_images(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_stone_skin(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_astral_walk(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_teleport(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_bless(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_infravision(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_true_seeing(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_blindness(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_light(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_cont_light(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_calm(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_web(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_clone(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_control_weather(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_create_food(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_create_water(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_water_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_flying(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_fly_group(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_heroes_feast(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_cure_blind(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_cure_critic(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_cure_light(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_cure_serious(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_refresh(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_second_wind(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_shield(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_curse(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_detect_evil(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_detect_invisibility(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_detect_magic(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_detect_poison(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_dispel_evil(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_dispel_good(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_faerie_fire(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_enchant_weapon(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_heal(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_invisibility(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_locate_object(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_poison(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_protection_from_evil(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_protection_from_evil_group(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_remove_curse(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_remove_poison(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_remove_paralysis(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_sanctuary(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_fireshield(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_sleep(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_strength(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_ventriloquate(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_word_of_recall(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_summon(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_charm_person(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_charm_monster(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_sense_life(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_identify(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_dragon_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *potion);
void cast_fire_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_frost_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_acid_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_gas_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_lightning_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_knock(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_know_alignment(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_weakness(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_dispel_magic(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_animate_dead(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_succor(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_paralyze(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_fear(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_turn(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_faerie_fog(byte level, struct char_data *ch, const char *arg, int type, struct char_data *victim, struct obj_data *tar_obj);
void cast_poly_self(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_minor_creation(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_conjure_elemental(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_cacaodemon(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mon_sum1(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mon_sum2(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mon_sum3(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mon_sum4(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mon_sum5(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mon_sum6(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mon_sum7(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_tree_travel(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_speak_with_plants(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_transport_via_plant(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_haste(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_slow(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_reincarnate(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_changestaff(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_pword_kill(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_pword_blind(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_chain_lightn(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_scare(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_familiar(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_aid(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_holyword(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_unholyword(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_golem(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_command(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_change_form(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_shillelagh(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_goodberry(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_elemental_blade(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_animal_growth(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_insect_growth(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_creeping_death(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_commune(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_feeblemind(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_animal_summon_1(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_animal_summon_2(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_animal_summon_3(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_fire_servant(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_earth_servant(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_water_servant(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_wind_servant(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_veggie_growth(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_charm_veggie(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_tree(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_animate_rock(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_travelling(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_animal_friendship(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_invis_to_animals(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_slow_poison(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_entangle(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_snare(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_gust_of_wind(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_barkskin(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_warp_weapon(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_heat_stuff(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_sunray(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_find_traps(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_firestorm(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_dust_devil(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_know_monster(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_silence(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_dragon_ride(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_mount(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_sending(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_portal(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_teleport_wo_error(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_globe_darkness(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_globe_minor_inv(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_globe_major_inv(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_energy_drain(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_dragon_breath(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_anti_magic_shell(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_comp_languages(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_fire(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_cold(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_energy(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_elec(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_enchant_armor(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_messenger(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_dragon_breath_fire(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_dragon_breath_frost(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_dragon_breath_elec(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_dragon_breath_acid(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_prot_dragon_breath_gas(byte level, struct char_data *ch, const char *arg, int type, struct char_data *tar_ch, struct obj_data *tar_obj);
#endif // __SPELLS2_HPP
