
/*$Id: status.h,v 1.2 2002/02/13 12:30:59 root Exp $
*/
#ifndef __STATUS
#define __STATUS 1
#define STATUS_BEFORELOOP      "BEFORELOOP"
#define STATUS_INITLOOP        "INITLOOP"
#define STATUS_AFTERPCOM       "AFTERPCOM"
#define STATUS_PULSEZONE       "PULSEZONE"
#define STATUS_PULSERIVER      "PULSERIVER"
#define STATUS_PULSETELEPORT   "PULSETELEPORT"
#define STATUS_PULSEVIOLENCE   "PULSEVIOLENCE"
#define STATUS_PERFORMVIOLENCE "PERFORMVIOLENCE"
#define STATUS_MUDHOUR         "MUDHOUR"
#define STATUS_AFFECTUPDATE    "AFFECTUPDATE"
#define STATUS_ENDLOOP         "ENDLOOP"
#define STATUS_CALLINGSCRIPT   "CALLINGSCRIPT"
#define STATUS_ENDSCRIPT       "ENDSCRIPT"
#define STATUS_CALLINGSPEC     "CALLINGSPEC"
#define STATUS_ENDSPEC         "ENDSPEC"

#define STATUS_OTCBEFORELOOP   "OTCBEFORELOOP"
#define STATUS_OTCREALOBJECT   "OTCREALOBJECT"
#define STATUS_OTCREADOBJECT   "OTCREADOBJECT"
#define STATUS_OTCCOPYVALUE    "OTCCOPYVALUE"
#define STATUS_OTCFREESTRING   "OTCFREESTRING"
#define STATUS_OTCALLOCSTRING  "OTCALLOCSTRING"
#define STATUS_OTCCOPYSTRING   "OTCCOPYSTRING"
#define STATUS_OTCCOPYAFFECT   "OTCCOPYAFFECT"
#define STATUS_OTCBAGTREE      "OTCBAGTREE"
#define STATUS_OTCENDLOOP      "OTCENDLOOP"
#define STATUS_OTCAFTERLOOP    "OTCAFTERLOOP"

#define STATUS_MAX             25


void PrintStatus(int level);
void PrintStatus();
#endif
#include "signals.hpp"
