name: Build
description: Full automated build and deployment pipeline

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        description: Dry run
        required: false
        default: true
      build_env:
        type: string
        description: The environment to build
        required: true
        default: devel
  push:
    branches:
      - "feature/*"
      - "release/*"
    tags:
      - "x*"
      - "r*"
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
      - "feature/*"
      
jobs:
  def:
    uses: NebbieArcane/Actions/.github/workflows/server-environment.yml@main
    secrets: inherit
  compile:
    needs: def
    if: needs.def.outputs.selected_env != 'ignore'
    uses: NebbieArcane/Actions/.github/workflows/server-compile.yml@main
    with:
      build_env: ${{ needs.def.outputs.selected_env }}
      dryrun: true
    secrets: inherit
  dockerize:
    needs: 
      - def
      - compile
    if: needs.def.outputs.selected_env != 'ignore'
    uses: NebbieArcane/Actions/.github/workflows/server-dockerize.yml@main
    with:
      build_env: ${{ needs.def.outputs.selected_env }}
      dryrun: true
    secrets: inherit    
            
