name: Build devel

on:
  workflow_call:
    inputs:
      build_env:
        type: string
        description: The environment to build
        required: true
        default: devel

jobs:
  build:
    environment:
      name: ${{ inputs.build_env }}
      deployment: false
    runs-on: ubuntu-latest
    container:
      image: nebbiearcane/mudcompiler:latest
      options: --entrypoint ""
    env:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    steps:
      - uses: NebbieArcane/Actions/compile@main
        with:
          build_env: devel
          mysql_host: ${{ vars.MYSQL_HOST }}
          mysql_user: ${{ vars.MYSQL_USER }}
          mysql_db: ${{ vars.MYSQL_DB }}
          mysql_password: ${{ secrets.MYSQL_PASSWORD }}
          mysql_port: ${{ vars.MYSQL_PORT }}
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: latest,prerelease,release
          dryrun: true
      
            
