name: Build devel

on:
    workflow_dispatch:
    push:
      branches:
        - feature/*
jobs:
  build:
    # if: ${{ contains(github.base_ref, vars.DEVEL_BRANCH ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "Base ref: ${{ github.ref }}"
          echo "DEVEL_BRANCH: ${{ vars.DEVEL_BRANCH }}"
    #   - uses: ./actions/compile.yml
