name: Dockerize staging

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build devel"]
    branches: [main]
    types: 
      - completed

jobs:

  call-dockerize-stagingl:
    uses: NebbieArcane/Actions/.github/workflows/dockerize.yml@main
    with:
      build_env: staging
    secrets: inherit


            
