name: Dockerize production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build devel"]
    branches: [main]
    types: 
      - completed

jobs:

  call-dockerize-production:
    uses: NebbieArcane/Actions/.github/workflows/dockerize.yml@main

    with:
      build_env: production
    secrets: inherit


            
