name: Dockerize devel

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build devel"]
    branches: [main]
    types: 
      - completed
  push:
    branches:
      - "feature/odb-discovery"

jobs:

  call-dockerize-devel:
    uses: NebbieArcane/ActionsServer/.github/workflows/dockerize.yml
    with:
      build_env: devel
    secrets: inherit


            
